### ISSUE TITLE
Buy/SellNotifications not working on Poloniex

### ISSUE THREAD

**Issue by abien** [mehtadone/CryptoGramBot#1]
The bot will happily report hourly balances but i could not convince it to msg me on trades on poloniex.

Not sure what logs to provide, here is my config:

```{
  "General": {
    "DatabaseLocation": "database\\cryptogrambot.sqlite"
  },
  "Coinigy": {
    "Enabled": "true",
    "SendHourlyUpdates": "false",
    "Key": "xxx",
    "Secret": "xxx",
    "Endpoint": "https://api.coinigy.com/api/v1/"
  },
  "Telegram": {
    "BotToken": "xxx",
    "ChatId": "xxx"
  },
  "Bittrex": {
    "Enabled": "false",
    "Key": "",
    "Secret": "",
    "SendHourlyUpdates": "false",
    "SellNotifications": "false",
    "BuyNotifications": "false"
  },
  "Poloniex": {
    "Enabled": "true",
    "Key": "xxx",
    "Secret": "xxx",
    "SendHourlyUpdates": "false",
    "SellNotifications": "true",
    "BuyNotifications": "true"
  },
  "BagManagement": {
    "Enabled": "false",
    "PercentageDrop": "30"
  },
  "DustNotification": {
    "Enabled": "true",
    "BtcAmount": "0.0005"
  }
}```

**Comment by mehtadone** [comment]
Your config file looks ok except for ``` at the end of the file. The config is dynamically converted into C# objects so any small typo can throw the whole thing. 

If you are still not getting any trad enotifications, attach your log file. This is found in the log folder of your installation. 

Thanks

**Comment by T1aMat** [comment]
Same thing for me. But with normal cfg.
Ubuntu 16.04
[CryptoGramBot-20171002.log](https://github.com/mehtadone/CryptoGramBot/files/1348687/CryptoGramBot-20171002.log)

**Comment by abien** [comment]
> Your config file looks ok except for ``` at the end of the file. 
This was a markdown mistake here on github, the config is okay.

I have attached my logs here:
[CryptoGramBot-20171002.zip](https://github.com/mehtadone/CryptoGramBot/files/1348971/CryptoGramBot-20171002.zip)

I would like to point your attention to these lines:
```
2017-10-02 00:27:33.035 +02:00 [Error] Error in getting new orders from poloniex
The remote server returned an error: (422) .
```
I think this is a known issue with the polo API. Its rate limits are pretty stupid and count per account - not per api key. After this it seems the bot does not try again.

**Comment by abien** [comment]
I just realized something else: The box my TG-Bot runs from is equipped with Elroys proxybot. Hence all requests for poloniex.com are handel through the proxy. Gunbot or Sjakil's GUI had to be started with `NODE_TLS_REJECT_UNAUTHORIZED=0 ./gunthy-gui-linux-x64` to not complain about the SSL Cert error. Maybe this is of relevance here?

**Comment by mehtadone** [comment]
I think the 422 error is a red herring. The bot does try again as seem in these lines: 
2017-10-02 07:42:31.422 +02:00 [Information] Adding new trades to database

The bug is either that polo is returning no trades or the code thinks that none of the trades are new.

**Comment by abien** [comment]
With Version 0.0.139 i am now receiving buy messages from poloniex. Havent had a sale since but @T1aMat reported earlier that its working for him. I assume this issue is solved.

**Comment by mehtadone** [comment]
Glad to hear. Please comment on here if it is not.
