### ISSUE TITLE
Wrong Poloniex Summary

### ISSUE THREAD

**Issue by crack00r** [mehtadone/CryptoGramBot#12]
![image](https://user-images.githubusercontent.com/6163329/32147415-35f260c6-bce7-11e7-9d92-104ca5678f85.png)

i just get -100% and -66%, this cant be true :D 

this was yesterday, same error
![image](https://user-images.githubusercontent.com/6163329/32147425-65248018-bce7-11e7-8d42-d514ce377c94.png)

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/32479923-706433b4-c38c-11e7-8742-443a6dbbf5a3.png)

**Comment by mehtadone** [comment]
The issue is that BTC is classed as a bag I think. That shouldn't show the difference since bought as the CryptoGramBot is setup to track btc vs altcoin trades
