### ISSUE TITLE
dotnet CryptoGramBot.dll does not exist

### ISSUE THREAD

**Issue by Marenqo** [mehtadone/CryptoGramBot#16]
Not sure why cos I a noob, but command prompt says that dotnet CryptoGramBot.dll does not exist?

C:\Users\Administrator\Documents\CryptoGramBot-master (1)\CryptoGramBot-master>dotnet CryptoGramBot.dll
The application to execute does not exist: 'C:\Users\Administrator\Documents\CryptoGramBot-master (1)\CryptoGramBot-master\CryptoGramBot.dll'

C:\Users\Administrator\Documents\CryptoGramBot-master (1)\CryptoGramBot-master>pause
Press any key to continue . . .

**Comment by AnikoV** [comment]
@Marenqo Hello, are you install .NET core sdk?

**Comment by mehtadone** [comment]
It seems you have downloaded the source not the compiled release binaries

**Comment by Marenqo** [comment]
@mehtadone 

You are correct, thanks for that
