### ISSUE TITLE
Add Binance to cryptogram bot

### ISSUE THREAD

**Issue by cryptotrader-1** [mehtadone/CryptoGramBot#20]
Add Binance to cryptogram!

**Comment by mehtadone** [comment]
In regards to commissions for binance, you can either pay in BTG or BTC. If you pay via BTG, how would you want the profit % to show as BTG was never part of the transaction.

**Comment by cryptotrader-1** [comment]
Hey Mehtadone thanks for looking into this. 
I’m guessing you mean BNB not BTG right? 

I would presume if it can’t automatically be taken into account it would be better then to do just take the fee as 0.1% even if you did have BNB to reduce fees. Probably better to be conservative then people will get happy when they have more money than the cryptogram bot shows ;)

**Comment by cryptotrader-1** [comment]
Also the 50% reduction in fees will be reduced moving forward. So I would guess wouldn’t be worth the effort to try to get it 100% right unless it can be automated that it picks it up
