### ISSUE TITLE
Feature Request: Add timeout between api requests

### ISSUE THREAD

**Issue by s0r0s** [mehtadone/CryptoGramBot#52]
CryptoGram Bot makes frequent requests. In conjunction with gunbot requests it causes IP ban by exchanges (Binance). Something like "BOT_DELAY" in config file will solve this issue.

**Comment by rsix08** [comment]
agreed,I turned off the bot  for now

**Comment by rigide** [comment]
In the last 12 hours, Binance has definitely restricted their max api requests per minute.
Just in the bot startup time between getting the 24h balance and the first trade check, you get ip banned 15min.
Requesting open orders makes it worse with even more requests.
We definitely need a minimum "BOT_DELAY" setting for ALL combined api requests (24h balance, trades, open orders, daily notifications, hourly updates, etc)

**Comment by nnation** [comment]
Yeah, this is a big one. Needed urgently, it would be best to implement in a way that we can go to the config and change it at will.

**Comment by snahsiub** [comment]
I would like this as well, because of this one, my buy/sell orders (from tradingview and entered via API using a bot) also didnt go through.

**Comment by BobWatson** [comment]
Please don't do this with a delay - please use websockets instead (maybe after a slow-roll on getting the initial trades, if needed) as they do not have the rate limit issue, and remove the requirement to poll.

**Comment by rigide** [comment]
"siwtom" has hard coded the timeout to 2mins and recompiled. Seems to be working..

https://github.com/siwtom/CryptoGramBot
https://github.com/siwtom/CryptoGramBot/releases

**Comment by siwtom** [comment]
I have just make two new builds, first for 2mins limited 800 request, and 1min limited 10 request.
Not yet tested!

**Comment by rigide** [comment]
I noticed the change on your github page but it didn't make it into your release. Still checks every 1 minute although I didn't get IP banned before noticing. Turned it back off for now.

**Comment by nnation** [comment]
@siwtom I still say its best to place this in a config file. And @BobWatson if the frequent poll are removed, how will they now if a buy or sell was executed?

**Comment by snahsiub** [comment]
How can i use that hardcoded version?

**Comment by rigide** [comment]
@siwtom please compile with 2 minute rate limit so we can use it :)

**Comment by snahsiub** [comment]
Yes please, I feel crippled without Binance. And, can you add Bitfinex as well? :)

**Comment by BobWatson** [comment]
@nnation the same info is available via websockets, which don’t have a rate limit. People run more than one app - the more apps using ws (esp. for info that is better ‘pushed’, like a trade), the less contention between them.

**Comment by rsix08** [comment]
Is there a new version out somewhere
