### ISSUE TITLE
Incorrect parameters writing to pairs file

### ISSUE THREAD

**Issue by Blueskydan** [mehtadone/CryptoGramBot#75]
Hello,  I have a small Issue with the pairs file PT Feeder writes every 5 minutes.

I have bought PT Feeder a week ago and I'm still tweaking it

Since acouple of hours ago, the PTF does not write the right instructions to the pairs file. Ex: LTC 

Altough, I've specified the LongTerm parameters for the way I see it fit

"LongerTermPriceChange": {
    "Configs": [
      {
        "MaxPriceTrendPercentageChange": "-6",
        "SellOnlyMode": "true"
      },
      {
        "MaxPriceTrendPercentageChange": "0"
      },
      {
        "MaxPriceTrendPercentageChange": "7",
        "SellOnlyMode": "true"

the LTC stopped going into SOM mode while  Price change (2880): 21.27%

#------------------BTC/LTC------------------
# Last Price: 0.021918
# Volume: 5591.2949
# Price change (60): -2.15%
# Price change (2880): 21.27%
# Upside volatility: 0.2%
# Downside volatility: 0.1%

BTC-LTC_trading_enabled = true
BTC-LTC_max_cost = 0.035
BTC-LTC_min_buy_balance = 0.2
BTC-LTC_trailing_profit = 0.11
BTC-LTC_trailing_buy = 0.035
BTC-LTC_buy_value = -0.45
BTC-LTC_buy_value_limit = 0
BTC-LTC_DCA_enabled = false
BTC-LTC_sell_value = 0.6
BTC-LTC_max_buy_spread = 1.2
BTC-LTC_min_profit = 0.7
BTC-LTC_min_buy_volume = 300
BTC-LTC_min_buy_price = 0.00007

Can you please advise ?

Thank you

**Comment by mehtadone** [comment]
Wrong project mate.

But this is a maximum.

"MaxPriceTrendPercentageChange": "7",
"SellOnlyMode": "true"

So anything above 7 will go to defaults. If I want anything higher than 0, you need a massive number instead of 0 like 100000 or something
