### ISSUE TITLE
Sell message not applying timezone offset correctly to the bought-on datetime

### ISSUE THREAD

**Issue by gambcl** [mehtadone/CryptoGramBot#78]
The timezone offset appears to be applied twice to the lastbought datetime, resulting in an incorrect time being displayed.

**Comment by pookzta** [comment]
Could someone please help me apply this fix? I downloaded the .zip version of CryptoGramBot, and I can't find the file to modify to apply this fix. There is no EventBus folder within the CryptoGramBot folder, and I can't locate the "TradeNotificationHandler.cs" anywhere else within the folder. Any help locating the "TradeNotificationHandler.cs" file so I can apply this fix would be greatly appreciated. Thank you. -Abe
